# Generated by Django 5.0.4 on 2024-05-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.PositiveIntegerField(max_length=10)),
                ('room_type', models.CharField(choices=[('Standart', 'Standart'), ('Deluxe', 'Deluxe'), ('Suite', 'Suite')], max_length=10)),
                ('capacity', models.PositiveIntegerField()),
                ('amenities', models.TextField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_reversed', models.BooleanField(default=False)),
            ],
        ),
    ]
