# Generated by Django 4.2.4 on 2024-05-14 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_migrate_unique_brands'),
    ]

    operations = [
    ]
