# Generated by Django 4.2.4 on 2024-05-14 09:14

from django.db import migrations


def age_group_information(apps, schema_editor):
    person_model = apps.get_model('main_app', 'Person')
    all_persons = person_model.objects.all()

    for person in all_persons:
        if person.age <= 12:
            person.age_group = 'Child'
        elif person.age <= 17:
            person.age_group = 'Teen'
        else:
            person.age_group = 'Adult'

    person_model.objects.bulk_update(all_persons, ['age_group'])


def reverse_age_group_information(apps, schema_editor):
    person_model = apps.get_model('main_app', 'Person')
    all_persons = person_model.objects.all()

    for person in all_persons:
        person.age_group = 'No age group'

    person_model.objects.bulk_update(all_persons, ['age_group'])


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0011_person'),
    ]

    operations = [migrations.RunPython(age_group_information, reverse_code=reverse_age_group_information)
                  ]
