# Generated by Django 4.2.4 on 2024-05-14 09:23

from django.db import migrations


def set_price(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    all_smartphones = smartphone_model.objects.all()

    for smartphone in all_smartphones:
        smartphone.price = len(smartphone.brand) * 120
        smartphone.save()


def set_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    all_smartphones = smartphone_model.objects.all()

    for smartphone in all_smartphones:
        if smartphone.price >= 750:
            smartphone.category = 'Expensive'
        else:
            smartphone.category = 'Cheap'
        smartphone.save()


def set_price_and_category(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)


def revert_price_and_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    all_smartphones = smartphone_model.objects.all()

    for sp in all_smartphones:
        sp.price = 0
        sp.category = 'empty'
        sp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_smartphone'),
    ]

    operations = [migrations.RunPython(set_price_and_category, reverse_code=revert_price_and_category)
    ]
