# Generated by Django 4.2.4 on 2024-05-14 09:36
from datetime import timedelta

from django.db import migrations


def delivery_and_warranty_update(apps, schema_editor):
    order_model = apps.get_model('main_app', 'Order')

    all_orders = order_model.objects.all()

    for order in all_orders:
        if order.status == 'Pending':
            order.delivery = order.order_date + timedelta(days=3)
            order.save()
        elif order.status == 'Completed':
            order.warranty = '24 months'
            order.save()
        else:
            order.remove()


def revert_delivery_and_warranty_update(apps, schema_editor):
    order_model = apps.get_model('main_app', 'Order')

    all_orders = order_model.objects.all()

    for order in all_orders:
        if order.status == 'Pending':
            order.delivery = None
            order.save()
        elif order.status == 'Completed':
            order.warranty = 'No warranty'
            order.save()
        else:
            order.remove()




class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_order'),
    ]

    operations = [migrations.RunPython(delivery_and_warranty_update, reverse_code=revert_delivery_and_warranty_update)
    ]
